/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as DashboardPresentationsIndexRouteImport } from './routes/dashboard/presentations/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardPresentationsNewRouteImport } from './routes/dashboard/presentations/new'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard/events/new'
import { Route as DashboardEventsEventIdEditRouteImport } from './routes/dashboard/events/$eventId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPresentationsIndexRoute =
  DashboardPresentationsIndexRouteImport.update({
    id: '/dashboard/presentations/',
    path: '/dashboard/presentations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/dashboard/events/',
  path: '/dashboard/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPresentationsNewRoute =
  DashboardPresentationsNewRouteImport.update({
    id: '/dashboard/presentations/new',
    path: '/dashboard/presentations/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/dashboard/events/new',
  path: '/dashboard/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsEventIdEditRoute =
  DashboardEventsEventIdEditRouteImport.update({
    id: '/dashboard/events/$eventId/edit',
    path: '/dashboard/events/$eventId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/presentations/new': typeof DashboardPresentationsNewRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/presentations/': typeof DashboardPresentationsIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/presentations/new': typeof DashboardPresentationsNewRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/presentations': typeof DashboardPresentationsIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/presentations/new': typeof DashboardPresentationsNewRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/presentations/': typeof DashboardPresentationsIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/admin/'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/events/new'
    | '/dashboard/presentations/new'
    | '/dashboard/events/'
    | '/dashboard/presentations/'
    | '/dashboard/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/dashboard/events/new'
    | '/dashboard/presentations/new'
    | '/dashboard/events'
    | '/dashboard/presentations'
    | '/dashboard/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/admin/'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/events/new'
    | '/dashboard/presentations/new'
    | '/dashboard/events/'
    | '/dashboard/presentations/'
    | '/dashboard/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardPresentationsNewRoute: typeof DashboardPresentationsNewRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardPresentationsIndexRoute: typeof DashboardPresentationsIndexRoute
  DashboardEventsEventIdEditRoute: typeof DashboardEventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/presentations/': {
      id: '/dashboard/presentations/'
      path: '/dashboard/presentations'
      fullPath: '/dashboard/presentations/'
      preLoaderRoute: typeof DashboardPresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/dashboard/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/presentations/new': {
      id: '/dashboard/presentations/new'
      path: '/dashboard/presentations/new'
      fullPath: '/dashboard/presentations/new'
      preLoaderRoute: typeof DashboardPresentationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/dashboard/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/$eventId/edit': {
      id: '/dashboard/events/$eventId/edit'
      path: '/dashboard/events/$eventId/edit'
      fullPath: '/dashboard/events/$eventId/edit'
      preLoaderRoute: typeof DashboardEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardPresentationsNewRoute: DashboardPresentationsNewRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardPresentationsIndexRoute: DashboardPresentationsIndexRoute,
  DashboardEventsEventIdEditRoute: DashboardEventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
